--------------------------------------------------------
--  File created - Sunday-January-03-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EQUIPEMAINTENANCE
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."EQUIPEMAINTENANCE" 
   (	"EQUIPEID" NUMBER, 
	"CHEFEQUIPE" VARCHAR2(20 CHAR), 
	"SPECIALITEE" VARCHAR2(20 BYTE), 
	"NOMBREREQUETTES" NUMBER(*,0), 
	"DATERQ" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into KHALIL3.EQUIPEMAINTENANCE
SET DEFINE OFF;
Insert into KHALIL3.EQUIPEMAINTENANCE (EQUIPEID,CHEFEQUIPE,SPECIALITEE,NOMBREREQUETTES,DATERQ) values (12,'juyhg','Biomedicale',12,null);
Insert into KHALIL3.EQUIPEMAINTENANCE (EQUIPEID,CHEFEQUIPE,SPECIALITEE,NOMBREREQUETTES,DATERQ) values (8,'mm','Informatique',7,null);
Insert into KHALIL3.EQUIPEMAINTENANCE (EQUIPEID,CHEFEQUIPE,SPECIALITEE,NOMBREREQUETTES,DATERQ) values (5,'mourad','Reparation',14,null);
Insert into KHALIL3.EQUIPEMAINTENANCE (EQUIPEID,CHEFEQUIPE,SPECIALITEE,NOMBREREQUETTES,DATERQ) values (2,'marwa','Biomedicale',12,null);
Insert into KHALIL3.EQUIPEMAINTENANCE (EQUIPEID,CHEFEQUIPE,SPECIALITEE,NOMBREREQUETTES,DATERQ) values (6,'wdefrg','Informatique',3,null);
--------------------------------------------------------
--  DDL for Index EQUIPEMQINTENQNCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALIL3"."EQUIPEMQINTENQNCE_PK" ON "KHALIL3"."EQUIPEMAINTENANCE" ("EQUIPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EQUIPEMAINTENANCE
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."EQUIPEMAINTENANCE" ADD CONSTRAINT "EQUIPEMQINTENQNCE_PK" PRIMARY KEY ("EQUIPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KHALIL3"."EQUIPEMAINTENANCE" MODIFY ("EQUIPEID" NOT NULL ENABLE);
