--------------------------------------------------------
--  File created - Sunday-January-03-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REQUETTES
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."REQUETTES" 
   (	"REFERENCE" NUMBER, 
	"EQUIPEID" NUMBER, 
	"TYPEMAINTENANCE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"SERVICE" VARCHAR2(20 BYTE), 
	"DATEAAJOUT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into KHALIL3.REQUETTES
SET DEFINE OFF;
Insert into KHALIL3.REQUETTES (REFERENCE,EQUIPEID,TYPEMAINTENANCE,ETAT,SERVICE,DATEAAJOUT) values (753,8,'Installation','Resolu','Urgence',to_date('01-JAN-00','DD-MON-RR'));
Insert into KHALIL3.REQUETTES (REFERENCE,EQUIPEID,TYPEMAINTENANCE,ETAT,SERVICE,DATEAAJOUT) values (8574,12,'Reparation','Resolu','Secretariat',to_date('01-JAN-00','DD-MON-RR'));
Insert into KHALIL3.REQUETTES (REFERENCE,EQUIPEID,TYPEMAINTENANCE,ETAT,SERVICE,DATEAAJOUT) values (586,5,'Curative','Resolu','Psychiatrie',to_date('01-JAN-00','DD-MON-RR'));
Insert into KHALIL3.REQUETTES (REFERENCE,EQUIPEID,TYPEMAINTENANCE,ETAT,SERVICE,DATEAAJOUT) values (86521,2,'Preventive','Resolu','Urgence',to_date('01-JAN-00','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index REQUETTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALIL3"."REQUETTES_PK" ON "KHALIL3"."REQUETTES" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REQUETTES
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."REQUETTES" ADD CONSTRAINT "REQUETTES_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KHALIL3"."REQUETTES" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table REQUETTES
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."REQUETTES" ADD CONSTRAINT "REQUETTES_FK1" FOREIGN KEY ("EQUIPEID")
	  REFERENCES "KHALIL3"."EQUIPEMAINTENANCE" ("EQUIPEID") ENABLE;
