--------------------------------------------------------
--  File created - Wednesday-January-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANALYSE
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."ANALYSE" 
   (	"REFERENCE" NUMBER, 
	"TYPE_PRELEV" VARCHAR2(20 BYTE), 
	"MATRICULE" VARCHAR2(20 BYTE), 
	"CATEGORIE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHAMBRE
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."CHAMBRE" 
   (	"ID" NVARCHAR2(20), 
	"TYPE" NVARCHAR2(20), 
	"ETAGE" NUMBER, 
	"NUMERO_CHAMBRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMAINTENANCE
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."EQUIPEMAINTENANCE" 
   (	"EQUIPEID" NUMBER, 
	"CHEFEQUIPE" VARCHAR2(20 CHAR), 
	"SPECIALITEE" VARCHAR2(20 CHAR), 
	"NOMBREREQUETTES" NUMBER, 
	"DATERQ" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENTS
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."EQUIPEMENTS" 
   (	"NUMDESERIE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"MODELE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"CONDITION" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."FOURNISSEUR" 
   (	"NOM" VARCHAR2(20 CHAR), 
	"MATRICULE" VARCHAR2(20 CHAR), 
	"ADRESSE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICAMENT
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."MEDICAMENT" 
   (	"NOM" VARCHAR2(20 CHAR), 
	"TYPE" VARCHAR2(20 CHAR), 
	"QUANTITE" NUMBER, 
	"FOURNISSEUR" VARCHAR2(20 CHAR), 
	"DATE_EXP" DATE, 
	"REFERENCE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."PATIENT" 
   (	"CIN" NVARCHAR2(20), 
	"NOM" NVARCHAR2(20), 
	"PRENOM" NVARCHAR2(20), 
	"AGE" NUMBER, 
	"DUREE" NUMBER, 
	"DATE_ENTRER" DATE, 
	"ID" NVARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNEL
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."PERSONNEL" 
   (	"CIN" VARCHAR2(8 CHAR), 
	"NOM" VARCHAR2(20 CHAR), 
	"PRENOM" VARCHAR2(20 CHAR), 
	"TYPE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RENDEZ_VOUS
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."RENDEZ_VOUS" 
   (	"REFERENCE" NUMBER, 
	"DATE_RV" DATE, 
	"OBJET_RV" VARCHAR2(20 BYTE), 
	"CIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REQUETTES
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."REQUETTES" 
   (	"REFERENCE" NUMBER, 
	"EQUIPEID" NUMBER, 
	"TYPEMAINTENANCE" VARCHAR2(20 CHAR), 
	"ETAT" VARCHAR2(20 CHAR), 
	"SERVICE" VARCHAR2(20 CHAR), 
	"DATEAAJOUT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICE
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."SERVICE" 
   (	"ID_SERVICE" VARCHAR2(20 CHAR), 
	"CIN_CHEF" VARCHAR2(8 CHAR), 
	"TYPE_SERVICE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICULES
--------------------------------------------------------

  CREATE TABLE "KHALIL3"."VEHICULES" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"CATEGORIE" VARCHAR2(20 BYTE), 
	"MODELE" VARCHAR2(20 BYTE), 
	"DESINFECTATION" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into KHALIL3.ANALYSE
SET DEFINE OFF;
REM INSERTING into KHALIL3.CHAMBRE
SET DEFINE OFF;
Insert into KHALIL3.CHAMBRE (ID,TYPE,ETAGE,NUMERO_CHAMBRE) values ('1','individuelle',2,2);
Insert into KHALIL3.CHAMBRE (ID,TYPE,ETAGE,NUMERO_CHAMBRE) values ('5','à deux',2,2);
REM INSERTING into KHALIL3.EQUIPEMAINTENANCE
SET DEFINE OFF;
Insert into KHALIL3.EQUIPEMAINTENANCE (EQUIPEID,CHEFEQUIPE,SPECIALITEE,NOMBREREQUETTES,DATERQ) values (1,'nhgbfvc','Biomedicale',12,null);
Insert into KHALIL3.EQUIPEMAINTENANCE (EQUIPEID,CHEFEQUIPE,SPECIALITEE,NOMBREREQUETTES,DATERQ) values (2,'ujhytgrf','Reparation',15,null);
Insert into KHALIL3.EQUIPEMAINTENANCE (EQUIPEID,CHEFEQUIPE,SPECIALITEE,NOMBREREQUETTES,DATERQ) values (3,'fcghvj','Biomedicale',15,null);
Insert into KHALIL3.EQUIPEMAINTENANCE (EQUIPEID,CHEFEQUIPE,SPECIALITEE,NOMBREREQUETTES,DATERQ) values (74,'hgbfv','Reparation',18,null);
Insert into KHALIL3.EQUIPEMAINTENANCE (EQUIPEID,CHEFEQUIPE,SPECIALITEE,NOMBREREQUETTES,DATERQ) values (55,'hgf','Biomedicale',14,null);
Insert into KHALIL3.EQUIPEMAINTENANCE (EQUIPEID,CHEFEQUIPE,SPECIALITEE,NOMBREREQUETTES,DATERQ) values (5,'ali','Biomedicale',16,null);
REM INSERTING into KHALIL3.EQUIPEMENTS
SET DEFINE OFF;
Insert into KHALIL3.EQUIPEMENTS (NUMDESERIE,NOM,MODELE,TYPE,CONDITION,DESCRIPTION) values ('123145jkl8','irmT80','JGT123mlp','imagerie','bonne','good');
Insert into KHALIL3.EQUIPEMENTS (NUMDESERIE,NOM,MODELE,TYPE,CONDITION,DESCRIPTION) values ('mpl25ml123','irmt60','mp126mlk','imagerie','bonne','sensitive');
Insert into KHALIL3.EQUIPEMENTS (NUMDESERIE,NOM,MODELE,TYPE,CONDITION,DESCRIPTION) values ('183145jkl8','ctscan-xvin56','JGT123mlp','imagerie','bonne','specific');
Insert into KHALIL3.EQUIPEMENTS (NUMDESERIE,NOM,MODELE,TYPE,CONDITION,DESCRIPTION) values ('152689hyt7','irmT50','clio','imagerie','bonne','cbhjnwfe');
REM INSERTING into KHALIL3.FOURNISSEUR
SET DEFINE OFF;
Insert into KHALIL3.FOURNISSEUR (NOM,MATRICULE,ADRESSE) values ('vdrfdr','sdssd','ddsdsdsds');
Insert into KHALIL3.FOURNISSEUR (NOM,MATRICULE,ADRESSE) values ('ggfdg','erfez','esfsefsd');
Insert into KHALIL3.FOURNISSEUR (NOM,MATRICULE,ADRESSE) values ('zqdqd','qdzqzqdz','qdzqzzqdqzd');
Insert into KHALIL3.FOURNISSEUR (NOM,MATRICULE,ADRESSE) values ('qsdq','qsdqsdsq','qdsqsdsqd');
Insert into KHALIL3.FOURNISSEUR (NOM,MATRICULE,ADRESSE) values ('ezzf','a','dsds');
Insert into KHALIL3.FOURNISSEUR (NOM,MATRICULE,ADRESSE) values ('ezzf','b','dsds');
Insert into KHALIL3.FOURNISSEUR (NOM,MATRICULE,ADRESSE) values ('ezzf','v','dsds');
Insert into KHALIL3.FOURNISSEUR (NOM,MATRICULE,ADRESSE) values ('ezzf','c','dsds');
REM INSERTING into KHALIL3.MEDICAMENT
SET DEFINE OFF;
Insert into KHALIL3.MEDICAMENT (NOM,TYPE,QUANTITE,FOURNISSEUR,DATE_EXP,REFERENCE) values ('azdazda','Comprime',40,'b',to_date('01-JAN-00','DD-MON-RR'),'qsdsqqsd');
Insert into KHALIL3.MEDICAMENT (NOM,TYPE,QUANTITE,FOURNISSEUR,DATE_EXP,REFERENCE) values ('fvfv','Seringue',0,'a',to_date('01-JAN-00','DD-MON-RR'),'dqzqqzd');
Insert into KHALIL3.MEDICAMENT (NOM,TYPE,QUANTITE,FOURNISSEUR,DATE_EXP,REFERENCE) values ('feefsfd','Seringue',5,'sdssd',to_date('01-JAN-00','DD-MON-RR'),'sdadsa');
Insert into KHALIL3.MEDICAMENT (NOM,TYPE,QUANTITE,FOURNISSEUR,DATE_EXP,REFERENCE) values ('zefez','Autre...',25,'v',to_date('01-JAN-00','DD-MON-RR'),'dsds');
Insert into KHALIL3.MEDICAMENT (NOM,TYPE,QUANTITE,FOURNISSEUR,DATE_EXP,REFERENCE) values ('jhgf','Seringue',1000,'b',to_date('01-JAN-00','DD-MON-RR'),'745');
REM INSERTING into KHALIL3.PATIENT
SET DEFINE OFF;
Insert into KHALIL3.PATIENT (CIN,NOM,PRENOM,AGE,DUREE,DATE_ENTRER,ID) values ('41','dfgh','ohg',85,15,to_date('06-JAN-21','DD-MON-RR'),'1');
Insert into KHALIL3.PATIENT (CIN,NOM,PRENOM,AGE,DUREE,DATE_ENTRER,ID) values ('7777','kk','kll',7,5,to_date('04-JAN-21','DD-MON-RR'),'1');
Insert into KHALIL3.PATIENT (CIN,NOM,PRENOM,AGE,DUREE,DATE_ENTRER,ID) values ('125','fhf','bb',12,21,to_date('06-JAN-21','DD-MON-RR'),'1');
Insert into KHALIL3.PATIENT (CIN,NOM,PRENOM,AGE,DUREE,DATE_ENTRER,ID) values ('889','dfghj','fgfhj',20,89,to_date('04-JAN-21','DD-MON-RR'),'1');
Insert into KHALIL3.PATIENT (CIN,NOM,PRENOM,AGE,DUREE,DATE_ENTRER,ID) values ('78','d','c',5,2,to_date('06-JAN-21','DD-MON-RR'),'1');
REM INSERTING into KHALIL3.PERSONNEL
SET DEFINE OFF;
Insert into KHALIL3.PERSONNEL (CIN,NOM,PRENOM,TYPE) values ('1476','chettaoui','khalil','maintenan');
Insert into KHALIL3.PERSONNEL (CIN,NOM,PRENOM,TYPE) values ('1478','ch','kh','requette');
REM INSERTING into KHALIL3.RENDEZ_VOUS
SET DEFINE OFF;
REM INSERTING into KHALIL3.REQUETTES
SET DEFINE OFF;
Insert into KHALIL3.REQUETTES (REFERENCE,EQUIPEID,TYPEMAINTENANCE,ETAT,SERVICE,DATEAAJOUT) values (74634,2,'Preventive','Non Resolu','Urgence',to_date('01-JAN-00','DD-MON-RR'));
Insert into KHALIL3.REQUETTES (REFERENCE,EQUIPEID,TYPEMAINTENANCE,ETAT,SERVICE,DATEAAJOUT) values (27552,1,'Curative','Non Resolu','Neurologie',to_date('01-JAN-00','DD-MON-RR'));
Insert into KHALIL3.REQUETTES (REFERENCE,EQUIPEID,TYPEMAINTENANCE,ETAT,SERVICE,DATEAAJOUT) values (2772,2,'Installation','Resolu','Pediatrie',to_date('01-JAN-00','DD-MON-RR'));
Insert into KHALIL3.REQUETTES (REFERENCE,EQUIPEID,TYPEMAINTENANCE,ETAT,SERVICE,DATEAAJOUT) values (86544,2,'Curative','Non Resolu','Pediatrie',to_date('01-JAN-00','DD-MON-RR'));
REM INSERTING into KHALIL3.SERVICE
SET DEFINE OFF;
Insert into KHALIL3.SERVICE (ID_SERVICE,CIN_CHEF,TYPE_SERVICE) values ('5','1478','maintenan');
Insert into KHALIL3.SERVICE (ID_SERVICE,CIN_CHEF,TYPE_SERVICE) values ('8','1477','maintenan');
REM INSERTING into KHALIL3.VEHICULES
SET DEFINE OFF;
Insert into KHALIL3.VEHICULES (NOM,CATEGORIE,MODELE,DESINFECTATION,DESCRIPTION) values ('crafter','A','13mlkipm5613f','protocole fait','tres rapide');
Insert into KHALIL3.VEHICULES (NOM,CATEGORIE,MODELE,DESINFECTATION,DESCRIPTION) values ('proace l2','C','ml12kj58mpa23','protocole fait','tres rapide');
Insert into KHALIL3.VEHICULES (NOM,CATEGORIE,MODELE,DESINFECTATION,DESCRIPTION) values ('clio','A','palk56mlpmaqw','protocole fait','rapide');
--------------------------------------------------------
--  DDL for Index REQUETTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALIL3"."REQUETTES_PK" ON "KHALIL3"."REQUETTES" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALIL3"."FOURNISSEUR_PK" ON "KHALIL3"."FOURNISSEUR" ("MATRICULE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEDICAMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALIL3"."MEDICAMENT_PK" ON "KHALIL3"."MEDICAMENT" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHAMBRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALIL3"."CHAMBRE_PK" ON "KHALIL3"."CHAMBRE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RENDEZ_VOUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALIL3"."RENDEZ_VOUS_PK" ON "KHALIL3"."RENDEZ_VOUS" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ANALYSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALIL3"."ANALYSE_PK" ON "KHALIL3"."ANALYSE" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMAINTENANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALIL3"."EQUIPEMAINTENANCE_PK" ON "KHALIL3"."EQUIPEMAINTENANCE" ("EQUIPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PATIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALIL3"."PATIENT_PK" ON "KHALIL3"."PATIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RENDEZ_VOUS
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."RENDEZ_VOUS" MODIFY ("REFERENCE" NOT NULL ENABLE);
  ALTER TABLE "KHALIL3"."RENDEZ_VOUS" ADD CONSTRAINT "RENDEZ_VOUS_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PATIENT
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."PATIENT" ADD CONSTRAINT "PATIENT_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KHALIL3"."PATIENT" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "KHALIL3"."PATIENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHAMBRE
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."CHAMBRE" ADD CONSTRAINT "CHAMBRE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KHALIL3"."CHAMBRE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."SERVICE" MODIFY ("ID_SERVICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICAMENT
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."MEDICAMENT" ADD CONSTRAINT "MEDICAMENT_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KHALIL3"."MEDICAMENT" ADD CONSTRAINT "MEDICAMENT_CHK1" CHECK (TYPE in ('Seringue','Comprime','Autre...')) ENABLE;
  ALTER TABLE "KHALIL3"."MEDICAMENT" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMAINTENANCE
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."EQUIPEMAINTENANCE" MODIFY ("EQUIPEID" NOT NULL ENABLE);
  ALTER TABLE "KHALIL3"."EQUIPEMAINTENANCE" ADD CONSTRAINT "EQUIPEMAINTENANCE_PK" PRIMARY KEY ("EQUIPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REQUETTES
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."REQUETTES" MODIFY ("REFERENCE" NOT NULL ENABLE);
  ALTER TABLE "KHALIL3"."REQUETTES" ADD CONSTRAINT "REQUETTES_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ANALYSE
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."ANALYSE" MODIFY ("REFERENCE" NOT NULL ENABLE);
  ALTER TABLE "KHALIL3"."ANALYSE" ADD CONSTRAINT "ANALYSE_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."FOURNISSEUR" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "KHALIL3"."FOURNISSEUR" MODIFY ("MATRICULE" NOT NULL ENABLE);
  ALTER TABLE "KHALIL3"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("MATRICULE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONNEL
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."PERSONNEL" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MEDICAMENT
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."MEDICAMENT" ADD CONSTRAINT "MEDICAMENT_FK1" FOREIGN KEY ("FOURNISSEUR")
	  REFERENCES "KHALIL3"."FOURNISSEUR" ("MATRICULE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PATIENT
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."PATIENT" ADD CONSTRAINT "PATIENT_FK1" FOREIGN KEY ("ID")
	  REFERENCES "KHALIL3"."CHAMBRE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUETTES
--------------------------------------------------------

  ALTER TABLE "KHALIL3"."REQUETTES" ADD CONSTRAINT "REQUETTES_FK1" FOREIGN KEY ("EQUIPEID")
	  REFERENCES "KHALIL3"."EQUIPEMAINTENANCE" ("EQUIPEID") ENABLE;
